// src/config.ts
/**
 * Loads calibrated thresholds and uncertainty settings generated by the
 * Week 4 calibration script.
 * The JSON is placed in `public/config/calibrated.json` and is fetched
 * at runtime. Consumers can import the exported `configPromise` which
 * resolves to an object containing `tau`, `uncertainty_high`, and
 * `uncertainty_very_high`.
 */
export interface CalibratedConfig {
    tau: number;
    uncertainty_high: number;
    uncertainty_very_high: number;
}

// Fetch once on module load; the promise can be awaited wherever needed.
export const configPromise: Promise<CalibratedConfig> = fetch('/config/calibrated.json')
    .then(r => {
        if (!r.ok) throw new Error('Failed to load calibrated config');
        return r.json();
    })
    .catch(err => {
        console.error(err);
        // Fallback defaults if the config is missing.
        return {
            tau: 0.55,
            uncertainty_high: 0.12,
            uncertainty_very_high: 0.20,
        } as CalibratedConfig;
    });
