// src/sw.ts
/// <reference lib="webworker" />
/**
 * Week 5: Custom Service Worker with Background Sync
 * 
 * This service worker handles:
 * - Background sync for Red/Amber cases
 * - Offline caching with Workbox
 * - Sync notifications
 */

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'

declare const self: ServiceWorkerGlobalScope

// Type declarations for Background Sync API
interface SyncEvent extends ExtendableEvent {
    tag: string
    lastChance: boolean
}

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// Cache API responses with NetworkFirst strategy
registerRoute(
    ({ url }) => url.pathname.startsWith('/api/'),
    new NetworkFirst({
        cacheName: 'api-cache',
        networkTimeoutSeconds: 10
    })
)

// Cache static assets with CacheFirst strategy
registerRoute(
    ({ request }) => request.destination === 'image' ||
        request.destination === 'font' ||
        request.destination === 'script' ||
        request.destination === 'style',
    new CacheFirst({
        cacheName: 'static-assets'
    })
)

// Week 5: Background Sync Event Handler
self.addEventListener('sync', (event) => {
    const syncEvent = event as unknown as SyncEvent
    console.log('[SW] Sync event triggered:', syncEvent.tag)

    if (syncEvent.tag === 'sync-cases') {
        syncEvent.waitUntil(syncPendingCases())
    }
})

/**
 * Sync all pending cases
 * This runs in the service worker context when background sync triggers
 */
async function syncPendingCases(): Promise<void> {
    try {
        console.log('[SW] Starting background sync for pending cases...')

        // Import sync service dynamically
        const { syncAllPending } = await import('./services/sync')

        const result = await syncAllPending()

        console.log(`[SW] Sync complete: ${result.success} succeeded, ${result.failed} failed`)

        // Show notification on sync completion
        if (result.success > 0) {
            await self.registration.showNotification('OralLight Sync Complete', {
                body: `${result.success} case${result.success > 1 ? 's' : ''} synced successfully`,
                icon: '/favicon.svg',
                badge: '/favicon.svg',
                tag: 'sync-success',
                requireInteraction: false
            })
        }

        if (result.failed > 0) {
            await self.registration.showNotification('OralLight Sync Failed', {
                body: `${result.failed} case${result.failed > 1 ? 's' : ''} failed to sync. Will retry later.`,
                icon: '/favicon.svg',
                badge: '/favicon.svg',
                tag: 'sync-failed',
                requireInteraction: true
            })
        }
    } catch (error) {
        console.error('[SW] Background sync failed:', error)

        // Show error notification
        await self.registration.showNotification('OralLight Sync Error', {
            body: 'Background sync encountered an error. Please try manual sync.',
            icon: '/favicon.svg',
            tag: 'sync-error',
            requireInteraction: true
        })
    }
}

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
    event.notification.close()

    // Open the app when notification is clicked
    event.waitUntil(
        self.clients.matchAll({ type: 'window' }).then((clients) => {
            // If app is already open, focus it
            for (const client of clients) {
                if (client.url.includes(self.registration.scope) && 'focus' in client) {
                    return client.focus()
                }
            }
            // Otherwise, open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow('/')
            }
        })
    )
})

// Handle online/offline events
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'ONLINE') {
        console.log('[SW] App is online, triggering sync...')
        // Trigger sync when app comes online
        if ('sync' in self.registration) {
            (self.registration as any).sync.register('sync-cases').catch((err: Error) => {
                console.error('[SW] Failed to register sync on online event:', err)
            })
        }
    }
})

console.log('[SW] Service Worker loaded with Background Sync support')
